// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB60gS5mTANNHEVOcSu9_0W7WO97Sf0YHM',
    appId: '1:1042979846594:web:bf4db941a186d974c0be5b',
    messagingSenderId: '1042979846594',
    projectId: 'jobslistings-69b5f',
    authDomain: 'jobslistings-69b5f.firebaseapp.com',
    storageBucket: 'jobslistings-69b5f.appspot.com',
    measurementId: 'G-G4K916FWWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaknAh0fX_OvkV2bWVwzDRX_J3FSEjP1g',
    appId: '1:1042979846594:android:f5e64f4bf888bc73c0be5b',
    messagingSenderId: '1042979846594',
    projectId: 'jobslistings-69b5f',
    storageBucket: 'jobslistings-69b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwk-h8ntQXlpyl-_N1w1g7U--AyZ6F9tE',
    appId: '1:1042979846594:ios:badb54b10a65ad27c0be5b',
    messagingSenderId: '1042979846594',
    projectId: 'jobslistings-69b5f',
    storageBucket: 'jobslistings-69b5f.appspot.com',
    iosClientId: '1042979846594-ar8b13ga1774glhmb0pqacf8vbg1k7gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwk-h8ntQXlpyl-_N1w1g7U--AyZ6F9tE',
    appId: '1:1042979846594:ios:badb54b10a65ad27c0be5b',
    messagingSenderId: '1042979846594',
    projectId: 'jobslistings-69b5f',
    storageBucket: 'jobslistings-69b5f.appspot.com',
    iosClientId: '1042979846594-ar8b13ga1774glhmb0pqacf8vbg1k7gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
